[package]
name = "dns-common"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion.workspace = true
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true