[workspace]
members = [
    "dns-common",
    "dns-client",
    "dns-server"
]

[workspace.dependencies]
anyhow = "1.0.69"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"